global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: '/metrics'

  - job_name: 'image-service'
    static_configs:
      - targets: ['image-service:8002']
    metrics_path: '/metrics'

  - job_name: 'video-service'
    static_configs:
      - targets: ['video-service:8003']
    metrics_path: '/metrics'

  - job_name: 'billing-service'
    static_configs:
      - targets: ['billing-service:8004']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8005']
    metrics_path: '/metrics'